start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000
start client\bin\Release\Client.exe 1000